"""GNDS-2.1 §9-10: ``styles``, and the chain each style was derived through.

**What a style is for.** §9.1: a data container holds several *forms*, each
tagged with the ``label`` of a style, and the ``styles`` node records how each
style was derived from another via ``derivedFrom``. The spec's own example is
exactly kika's situation — a ``crossSection`` holding a
``resonancesWithBackground`` form labelled ``eval`` and an ``XYs1d`` form
labelled ``recon``.

That is the structure kika has been missing. Today `endf.pendf` is a dict
hanging off the side of an ``ENDF`` object, populated by whichever reconstructor
the caller chose, with nothing recording *which* — which is the whole reason
``MF34_to_MG`` had to be made to raise rather than guess a σ. Here the
provenance is the model: a ``crossSectionReconstructed`` style whose
``derivedFrom`` names the ``evaluated`` style it came from.

**The ``realization`` style (§9.3) is the standards-blessed home for the Fe-56
perturbed ensemble.** §9.3 defines it for *"data that was randomly generated by
sampling from probability distributions and/or covariance matrices"*, and
§9.3.1 makes ``derivedFrom`` **required** on it: *"The derivedFrom node must
point to the evaluated style containing the covariances and/or probabilities
that were sampled to produce this realization."* Phase 8 emits the thesis
ensemble this way.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Iterator, List, Optional

from .quantities import PhysicalQuantity, RangeQuantity

__all__ = [
    "Style",
    "Evaluated",
    "Realization",
    "CrossSectionReconstructed",
    "AngularDistributionReconstructed",
    "CoulombPlusNuclearElasticMuCutoff",
    "Heated",
    "AverageProductData",
    "MonteCarlo_cdf",
    "GriddedCrossSection",
    "URR_probabilityTables",
    "HeatedMultiGroup",
    "SnElasticUpScatter",
    "Styles",
    "StyleError",
]


class StyleError(ValueError):
    """A ``styles`` node is inconsistent — a dangling or circular ``derivedFrom``."""


@dataclass
class Style:
    """Base for the §9 styles. ``label`` identifies it; forms refer to it by label."""

    label: str
    derivedFrom: Optional[str] = None
    date: Optional[str] = None

    #: The GNDS node name, which is *not* the class name lower-cased in every
    #: case (``MonteCarlo_cdf``, ``URR_probabilityTables``), so it is declared.
    gndsNodeName: str = field(default="style", init=False, repr=False)

    #: Whether §9 requires this style to name what it was derived from.
    derivedFromRequired: bool = field(default=False, init=False, repr=False)

    def __post_init__(self) -> None:
        if self.derivedFromRequired and not self.derivedFrom:
            raise StyleError(
                f"the {self.gndsNodeName!r} style requires derivedFrom (§9.3.1); "
                f"style {self.label!r} has none"
            )


def _style(nodeName: str, *, requiresDerivedFrom: bool = False):
    """Declare a concrete style class carrying its GNDS node name."""

    def decorate(cls):
        cls.gndsNodeName = nodeName
        cls.derivedFromRequired = requiresDerivedFrom
        return cls

    return decorate


@_style("evaluated")
@dataclass
class Evaluated(Style):
    """§9.2.1. Data as created by the evaluator. More than one is allowed.

    ``temperature`` and ``projectileEnergyDomain`` are children the schema makes
    **mandatory** on this style (``RS_EvaluatedType``), and all 558 neutron
    evaluations carry both. They are fields rather than reported losses because
    they are data: dropping the temperature leaves nothing distinguishing a 0 K
    evaluation from a broadened one, and dropping the domain leaves nothing
    saying what the evaluation was written *for* — which is not the same
    statement as the union of its reactions' domains.
    """

    library: Optional[str] = None
    version: Optional[str] = None
    temperature: Optional[PhysicalQuantity] = None
    projectileEnergyDomain: Optional[RangeQuantity] = None


@_style("realization", requiresDerivedFrom=True)
@dataclass
class Realization(Style):
    """§9.3.1. One sample drawn from the covariances of its ``derivedFrom`` style."""


@_style("crossSectionReconstructed")
@dataclass
class CrossSectionReconstructed(Style):
    """§9. Pointwise σ from resonance parameters plus background."""


@_style("angularDistributionReconstructed")
@dataclass
class AngularDistributionReconstructed(Style):
    """§9. Angular distributions reconstructed from resonance parameters."""


@_style("CoulombPlusNuclearElasticMuCutoff")
@dataclass
class CoulombPlusNuclearElasticMuCutoff(Style):
    """§9. Charged-particle elastic, with the small-angle divergence cut off."""

    muCutoff: Optional[float] = None


@_style("heated")
@dataclass
class Heated(Style):
    """§9. Doppler-broadened to a temperature."""

    temperature: Optional[object] = None  # a PhysicalQuantity in K


@_style("averageProductData")
@dataclass
class AverageProductData(Style):
    """§9."""


@_style("MonteCarlo_cdf")
@dataclass
class MonteCarlo_cdf(Style):  # noqa: N801 - GNDS node name, see NAMING.md
    """§9."""


@_style("griddedCrossSection")
@dataclass
class GriddedCrossSection(Style):
    """§9. Cross sections put onto a common grid — an ACE/processed representation."""


@_style("URR_probabilityTables")
@dataclass
class URR_probabilityTables(Style):  # noqa: N801 - GNDS node name, see NAMING.md
    """§9. Unresolved-region probability tables."""


@_style("heatedMultiGroup")
@dataclass
class HeatedMultiGroup(Style):
    """§9. Group-averaged at a temperature."""


@_style("SnElasticUpScatter")
@dataclass
class SnElasticUpScatter(Style):  # noqa: N801 - GNDS node name, see NAMING.md
    """§9."""


@dataclass
class Styles:
    """§9.1. The evaluation's styles, and the graph ``derivedFrom`` defines.

    Look-up is by label, because that is what a form carries. The chain
    resolution is the point of the node: given a processed form, walk back to
    the ``evaluated`` style it ultimately came from, and refuse to walk a cycle.
    """

    styles: List[Style] = field(default_factory=list)

    def __len__(self) -> int:
        return len(self.styles)

    def __iter__(self) -> Iterator[Style]:
        return iter(self.styles)

    def __bool__(self) -> bool:
        # A declared slot is *present* even when empty; only `len()` speaks to
        # content. Without this, `if suite.styles:` reads an evaluation that
        # models styles and has none yet as one that does not model them.
        return True

    def __getitem__(self, label: str) -> Style:
        for style in self.styles:
            if style.label == label:
                return style
        raise KeyError(
            f"no style labelled {label!r}; have {[s.label for s in self.styles]}"
        )

    def add(self, style: Style) -> None:
        if any(s.label == style.label for s in self.styles):
            raise StyleError(f"duplicate style label {style.label!r}")
        self.styles.append(style)

    def chain(self, label: str) -> List[Style]:
        """``[style, its parent, ..., the root]``.

        Raises on a dangling ``derivedFrom`` and on a cycle. A cycle is not a
        hypothetical: ``derivedFrom`` is a free-text label, so two styles naming
        each other is a single typo away, and the failure without this check is
        a hang rather than an error.
        """
        seen: List[str] = []
        out: List[Style] = []
        current: Optional[str] = label
        while current is not None:
            if current in seen:
                raise StyleError(
                    f"derivedFrom cycle: {' -> '.join(seen + [current])}"
                )
            seen.append(current)
            try:
                style = self[current]
            except KeyError as exc:
                raise StyleError(
                    f"style {seen[-2] if len(seen) > 1 else label!r} is derivedFrom "
                    f"{current!r}, which does not exist"
                ) from exc
            out.append(style)
            current = style.derivedFrom
        return out

    def rootOf(self, label: str) -> Style:
        """The style at the end of the ``derivedFrom`` chain."""
        return self.chain(label)[-1]

    def evaluatedFor(self, label: str) -> Evaluated:
        """The ``evaluated`` style a processed form ultimately derives from.

        This is the question ``MF34_to_MG`` could not answer and therefore had
        to refuse: *whose* σ am I weighting with. Here it is a graph walk.
        """
        for style in self.chain(label):
            if isinstance(style, Evaluated):
                return style
        raise StyleError(
            f"no evaluated style in the derivedFrom chain of {label!r}: "
            f"{[s.label for s in self.chain(label)]}"
        )

    @property
    def labels(self) -> List[str]:
        return [s.label for s in self.styles]
