"""Geometry dataclasses for WWINP files."""

from dataclasses import dataclass, field
from functools import cached_property

import numpy as np


@dataclass
class GeometryAxis:
    """A single geometry axis defined by coarse mesh segments.

    Each segment has a fine mesh ratio *q*, a coarse endpoint *p*, and a fine
    mesh count *s*.  The fine mesh is generated by subdividing each coarse
    segment into *s* equal intervals (when q = 1).

    Parameters
    ----------
    origin : float
        Starting coordinate of the axis.
    q : np.ndarray
        Fine mesh ratios per segment (float64).
    p : np.ndarray
        Coarse mesh endpoints per segment (float64).
    s : np.ndarray
        Number of fine meshes per segment (int32).
    """

    origin: float = 0.0
    q: np.ndarray = field(default_factory=lambda: np.empty(0, dtype=np.float64))
    p: np.ndarray = field(default_factory=lambda: np.empty(0, dtype=np.float64))
    s: np.ndarray = field(default_factory=lambda: np.empty(0, dtype=np.int32))

    @cached_property
    def coarse_mesh(self) -> np.ndarray:
        """Coarse mesh boundaries including the origin."""
        return np.concatenate(([self.origin], self.p))

    @cached_property
    def fine_mesh(self) -> np.ndarray:
        """Fine mesh boundaries including the origin."""
        points = [self.origin]
        current = self.origin
        for endpoint, n_fine in zip(self.p, self.s):
            step = (endpoint - current) / n_fine
            for i in range(1, n_fine + 1):
                points.append(current + step * i)
            current = endpoint
        return np.array(points, dtype=np.float64)

    @property
    def n_fine(self) -> int:
        """Total number of fine mesh bins on this axis."""
        return int(np.sum(self.s))


_AXIS_LABELS = {
    1: ("x", "y", "z"),
    2: ("r", "z", "theta"),
    3: ("r", "phi", "theta"),  # MCNP convention: (r, φ, θ)
}


@dataclass
class GeometryData:
    """Container for three geometry axes.

    The axes are always stored in the order they appear in the WWINP file
    (first, second, third axis).  Semantic labels depend on the geometry type.

    Parameters
    ----------
    axes : tuple[GeometryAxis, GeometryAxis, GeometryAxis]
        The three axes in file order.
    geometry_type : int
        1 = cartesian, 2 = cylindrical, 3 = spherical.
    """

    axes: tuple[GeometryAxis, GeometryAxis, GeometryAxis] = field(
        default_factory=lambda: (GeometryAxis(), GeometryAxis(), GeometryAxis())
    )
    geometry_type: int = 1

    @property
    def axis_labels(self) -> tuple[str, str, str]:
        return _AXIS_LABELS.get(self.geometry_type, ("a1", "a2", "a3"))

    @cached_property
    def fine_mesh(self) -> dict[str, np.ndarray]:
        """Fine mesh boundaries keyed by axis label."""
        labels = self.axis_labels
        return {labels[i]: self.axes[i].fine_mesh for i in range(3)}

    @cached_property
    def coarse_mesh(self) -> dict[str, np.ndarray]:
        """Coarse mesh boundaries keyed by axis label."""
        labels = self.axis_labels
        return {labels[i]: self.axes[i].coarse_mesh for i in range(3)}
